version: '3.8'

services:
  portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    container_name: portfolio-frontend-next
    image: portfolio-frontend:latest

    ports:
      - "${PORT:-3010}:3000"

    environment:
      - NODE_ENV=production

    env_file:
      - .env.production

    restart: unless-stopped

    networks:
      - portfolio-frontend-network

networks:
  portfolio-frontend-network:
    name: portfolio-frontend-network
    driver: bridge
