version: '3.8'

services:
  portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://217.76.53.136:4050}

    container_name: portfolio-frontend-next
    image: portfolio-frontend:latest

    ports:
      - "${PORT:-3050}:3000"

    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://217.76.53.136:4050}

    env_file:
      - .env.production

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

    networks:
      - portfolio-frontend-network

networks:
  portfolio-frontend-network:
    name: portfolio-frontend-network
    driver: bridge
